[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "https://privatrengoering.dk/*"
  to = "https://privaterengoring.dk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.privatrengoering.dk/*"
  to = "https://privaterengoring.dk/:splat"
  status = 301
  force = true

[dev]
  framework = "vite"
  command = "npm run dev:netlify"
  targetPort = 5175
  port = 8888
  publish = "dist"
  autoLaunch = true
  edge_functions = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "api"
  node_bundler = "esbuild"