[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"

[[redirects]]
  from = "https://privatrengoering.dk/*"
  to = "https://privaterengoring.dk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.privatrengoering.dk/*"
  to = "https://privaterengoring.dk/:splat"
  status = 301
  force = true

[dev]
  framework = "vite"
  command = "vite"
  env = { VITE_NETLIFY_DEV = "true", JWT_SECRET = "private-rengoring-super-secret-key-2024" }
  edge_functions = false
  targetPort = 5175
  port = 8888
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "api"
  node_bundler = "esbuild"